server:
  transport:
    sse:
      enabled: false
      address: 0.0.0.0:8080
      #baseURL: http://host.docker.internal:8080
      baseURL: http://0.0.0.0:8080
    stdio:
      enabled: true
    http:
      enabled: false
      address: 0.0.0.0:8081

  tools:
    # List of tools to disable if you don't want to serve them to the client/host.
    disabled: []

  chronosphere:
    apiURL: ${CHRONOSPHERE_ORG_NAME:""}.chronosphere.io
    # The API token for Chronosphere, used to authenticate requests.
    # Leave empty if forwarding bearer token.
    apiToken: ${CHRONOSPHERE_API_TOKEN:""}
    # Whether the organization uses LogScale for logs.
    # Must set logscaleURL and logscaleAPIToken if true.
    useLogscale: ${USE_LOGSCALE:false}
    # The URL for the logscale API if using LogScale for logs.
    logscaleURL: ${CHRONOSPHERE_ORG_NAME:""}.logs.chronosphere.io
    # The API token for LogScale if using LogScale for logs.
    logscaleAPIToken: ${LOGSCALE_API_TOKEN:""}
