server:
  transport:
    sse:
      enabled: true
      address: 0.0.0.0:8080
      #baseURL: http://host.docker.internal:8080
      baseURL: http://0.0.0.0:8080
    stdio:
      enabled: true

  tools:
    # List of tools to disable if you don't want to serve them to the client/host.
    disabled: []
